### ISSUE TITLE
Sync with changes merged after 6378d4bc06cd1bb1a209bd5fb63d10ef52d75eb4

### ISSUE THREAD

**Issue by zero323** [zero323/pyspark-stubs#230]
- [x] [SPARK-28969](https://github.com/apache/spark/commit/77e9b58d4f6dd06b1d2598845b1ba9657424bf9f#diff-6abddffa5e33baef494418540211c14e)  OneVsRestParams parity between scala and python - #226
- [x] [SPARK-22797](https://github.com/apache/spark/pull/25801) Bucketizer support multi-column  - #236
- [x] [SPARK-27463](https://github.com/apache/spark/pull/24981) Support Dataframe Cogroup via Pandas UDFs - #242
- [x] [SPARK-22796](https://github.com/apache/spark/pull/25812) Add multiple columns support to PySpark QuantileDiscretizer - #236
- [x] [SPARK-28985](https://github.com/apache/spark/pull/25776)  Add common classes (JavaPredictor / JavaClassificationModel / JavaProbabilisticClassifier) in PYTHON - #262
- [x] [SPARK-27659](https://github.com/apache/spark/pull/25515)  Allow PySpark to prefetch during toLocalIterator - #240
- [x] [SPARK-29142](https://github.com/apache/spark/pull/25859) Pyspark clustering models support column setters/getters/predict - #259
- [x] [SPARK-29258](https://github.com/apache/spark/pull/25940) parity between ml.evaluator and mllib.metrics - #243
- [x] [SPARK-29240](https://github.com/apache/spark/pull/25950) (no changes needed as we accept `Any`).
- [X] [SPARK-29143](https://github.com/apache/spark/pull/25908) Pyspark feature models support column setters/getters  - #278
- [x] [SPARK-29360](https://github.com/apache/spark/pull/26035) PySpark FPGrowthModel supports getter/setter - #279 
- [x] [SPARK-29269](https://github.com/apache/spark/pull/25947) Pyspark ALSModel support getters/setter - #282 
- [X] [SPARK-29116](https://github.com/apache/spark/pull/25929) Refactor py classes related to DecisionTree - #285 
- [X] [SPARK-29377](https://github.com/apache/spark/pull/26057) Parity between Scala ML tuning and Python ML tuning - #287
- [x] [SPARK-29381](https://github.com/apache/spark/pull/26103) / [FOLLOWUP] (https://github.com/apache/spark/pull/26142) Add _ before the XXXParams classes - #292
- [x] [SPARK-23578](https://github.com/apache/spark/pull/26064)  Binarizer support multi-column - #294
- [x] [SPARK-29464](https://github.com/apache/spark/pull/26130) PySpark ML should expose Params.clear() to unset a user supplied Param - #295
- [x] [SPARK-29235](https://github.com/apache/spark/pull/26038) Support avgMetrics in read/write of CrossValidatorModel (No changes required)
- [x] [SPARK-29499](https://github.com/apache/spark/pull/26148) Add mapPartitionsWithIndex for RDDBarrier - #296
- [x] [SPARK-29444](https://github.com/apache/spark/pull/26227) add doc and python parameter for ignoreNullFields in json generating - #297
- [X] [SPARK-29093](https://github.com/apache/spark/pull/26232)  Remove automatically generated param setters in _shared_params_code_gen.py - #298, #301
- [x] [SPARK-29566](https://github.com/apache/spark/pull/26247) Imputer should support single-column input/output - #302
- [x] [SPARK-29565](https://github.com/apache/spark/pull/26265) OneHotEncoder should support single-column input/output - #303
- [x] [SPARK-29627](https://github.com/apache/spark/pull/26288) Allow array_contains to take column instances (no changes needed as we accept Any).
- [x] [SPARK-29645](https://github.com/apache/spark/pull/26305) ML add param RelativeError - #304
- [x] [SPARK-29664](https://github.com/apache/spark/pull/26351) Column.getItem behavior is not consistent with Scala (No changes required)
- [x] [SPARK-29656](https://github.com/apache/spark/pull/26322) ML algs expose aggregationDepth - #305
- [x] [SPARK-29808](https://github.com/apache/spark/pull/26480) StopWordsRemover should support multi-cols - #306
- [x] [SPARK-16872](https://github.com/apache/spark/pull/26413) Impl Gaussian Naive Bayes Classifier #307
- [x] [SPARK-29959](https://github.com/apache/spark/pull/26596) Summarizer support more metrics - #308
- [x] [SPARK-27990](https://github.com/apache/spark/pull/26718) Add recursiveFileLookup option to Python DataFrameReader - #309
- [x] [SPARK-30091](https://github.com/apache/spark/pull/26730) Document mergeSchema option directly in the PySpark Parquet APIs - #310
- [x] [SPARK-30113](https://github.com/apache/spark/pull/26755) Expose mergeSchema option in PySpark's ORC APIs - #311
- [x] [SPARK-30146](https://github.com/apache/spark/pull/26774) Add setWeightCol to GBTs in PySpark - #312
- [x] [SPARK-29967](https://github.com/apache/spark/pull/26739) KMeans support instance weighting - #313
- [x] [SPARK-30231](https://github.com/apache/spark/pull/26861) Support explain mode in PySpark df.explain - #314
- [x] [SPARK-29224](https://github.com/apache/spark/pull/27000) Implement Factorization Machines as a ml-pipeline - #316
- [x] [SPARK-30247](https://github.com/apache/spark/pull/27020) GaussianMixtureModel in py side should expose gaussian - #318
- [x] [SPARK-30178](https://github.com/apache/spark/pull/26803) RobustScaler support large numFeatures (No changes required)
- [x] [SPARK-30102](https://github.com/apache/spark/pull/26735) GMM supports instance weighting - #319
- [x] [SPARK-30378](https://github.com/apache/spark/pull/27044) Add getter/setter in Python FM - #316
- [x] [SPARK-30358](https://github.com/apache/spark/pull/27082) ML expose predictRaw and predictProbability on Python side - #320
- [x] [SPARK-30144](https://github.com/apache/spark/pull/26838) Make MultilayerPerceptronClassificationModel extend MultilayerPerceptronParams #321
- [x]  [SPARK-30154](https://github.com/apache/spark/pull/26910) PySpark UDF to convert MLlib vectors to dense arrays - #317
- [x] [SPARK-30434](https://github.com/apache/spark/pull/27109) Move pandas related functionalities into 'pandas' sub-package - #327
- [x]  [SPARK-30452](https://github.com/apache/spark/pull/27122) Add predict and numFeatures in Python IsotonicRegressionModel - #322
- [x] [SPARK-30493](https://github.com/apache/spark/pull/27181) Remove OneVsRestModel setClassifier, setLabelCol and setWeightCol methods - #298

**Comment by zero323** [comment]
All done!
