### ISSUE TITLE
Sync with changes merged after 6502c66025718bf45e0e2ee12398b7b92da41a0c

### ISSUE THREAD

**Issue by zero323** [zero323/pyspark-stubs#315]
- [x] [SPARK-30377](https://github.com/apache/spark/pull/27168) Make Regressors extend abstract class Regressor - #325
- [x] [SPARK-30351](https://github.com/apache/spark/pull/27035) BisectingKMeans support instance weighting - #323
- [x] [SPARK-30498](https://github.com/apache/spark/pull/27196) Fix some ml parity issues between python and scala - #326 
- [x] [SPARK-9478](https://github.com/apache/spark/pull/27097) Add sample weights to Random Forest  - #324
- [x] [SPARK-29565](https://github.com/apache/spark/commit/1ef1d6caf259da3bc417444f63cb6cc782bc8cb9) add setInputCol/setOutputCol in OHEModel - #335
- [x] [SPARK-30533](https://github.com/apache/spark/pull/27241) Add classes to represent Java Regressors and RegressionModels - #339 
- [x]  [SPARK-30539](https://github.com/apache/spark/pull/27251) Add DataFrame.tail in PySpark - #338 
- [x] [SPARK-28264](https://github.com/apache/spark/pull/27165)  Support type hints in pandas UDF and rename/move inconsistent pandas UDF types - #349
- [x] [SPARK-30607](https://github.com/apache/spark/pull/27325) Add overlay wrappers for SparkR and PySpark - #347
- [x] [SPARK-30543](https://github.com/apache/spark/pull/27254) RandomForest add Param bootstrap to control sampling method - #348
- [x] [SPARK-30642](https://github.com/apache/spark/pull/27360)  LinearSVC blockify input vectors #356
- [x] [SPARK-30662](https://github.com/apache/spark/pull/27389) ALS/MLP extend HasBlockSize  - #358, #359
- [x] [SPARK-29093](https://github.com/apache/spark/pull/27397) FOLLOW-UP Remove duplicate setter - #360
- [x] [SPARK-30660](https://github.com/apache/spark/pull/27396) LinearRegression blockify input vectors - #361

**Comment by zero323** [comment]
All tasks have been resolved, and [Spark 3.0 was cut](http://apache-spark-developers-list.1001551.n3.nabble.com/Spark-3-0-branch-cut-and-code-freeze-on-Jan-31-tp28575p28803.html).
